show user
select * from tab;
CREATE TABLE COMPUTER_SPECS(PROCESSOR VARCHAR(30),RAM_GB NUMBER,RELEASE_DATE VARCHAR(30));
INSERT INTO computer_specs VALUES('&PROCESSOR',&RAM,'&RELEASE_DATE');      /*IS THE SUBSTITUTION METHOD OF ENTERING DATA INTO THE TABLE*/
SELECT * FROM computer_specs;
COMMIT;

/*  BY USING / WE CAN AGAIN EXECTE THE PREVIOUS QUERIES*/  

